dist: xenial
language: python
python:
  - 3.6
  - 3.7
before_install:
 - pip install --only-binary=all cython coveralls pysam
install:
 - python setup.py install
script:
 - python setup.py test
 - python -m coverage run --source=./ld_estimator -m unittest discover
after_success:
 - coveralls
